### ISSUE TITLE
Unable to compose classes containing a colon

### ISSUE THREAD

**Issue by fpauser** [salsify/ember-css-modules#135]
Escaped colons in css definitions should be unescaped when applied to html.

For example - this styles.scss:

```css
.fancy {
  composes: text-grey-dark hover\:text-grey-lightest from global;
}
```

together with this template:

```hbs
<span local-class="fancy">
  SAMPLE TEXT
</span>
```

produces the following incorrect html

```html
<div class="_fancy_iaj7hm text-grey-dark hover\:text-grey-lightest">
  SAMPLE TEXT
</div>
```

instead of this correct html:

```html
<div class="_fancy_iaj7hm text-grey-dark hover:text-grey-lightest">
  SAMPLE TEXT
</div>
```
