### ISSUE TITLE
In-repo-addon css files in 'my-addon/addon/styles' should not be processed

### ISSUE THREAD

**Issue by bartocc** [salsify/ember-css-modules#144]
My app has an in-repo-addon and this addon has the following CSS file in `lib/my-addon/addon/styles/foo.css`:

```css
/* lib/my-addon/addon/styles/foo.css */
.red {
  color: red;
}
```

Ember-cli automatically merges these CSS files into `vendor.css` and my app can use the CSS classes. So the following template would render the text in red:

```hbs
{{!-- app/templates.application.hbs --}}
<span class="red">I am red because the .red class is provided by my-addon</span>
```

But if I want to use `ember-css-modules` for the addon's components, `lib/my-addon/addon/styles/foo.css` seems to be processed and `vendor.css` will look like:

```css
/* dist/assets/vendor.css */
.red_1yx9rc {
  color: red;
}
```

and obviously, the `<span class="red">` won't be red anymore.

Is there a config that I am missing here or is this a limitation of `ember-css-modules`?

**Comment by dfreeman** [comment]
Hi @bartocc, sorry for the long silence here!

The short answer is that ECM intentionally doesn't treat the `styles` directory of an app or addon as special, since if you're using the classic (i.e. non-pods) project layout, that's where all the styles for your components and route templates go.

Fortunately there are a few different ways you can accomplish what I think you're describing. The last one in the list is what we tend to do in all our own internal addons and applications, and we design the classes to be consumed that way.

### Explicitly make the `.red` class global

In `lib/my-addon/addon/styles/foo.css`, you can write this to avoid having the class name be rewritten:

```css
:global(.red) {
  color: red;
}
```

Or, if you're using e.g. the `postcss-nested` plugin, you can put any number of global classes in a block:

```css
:global {
  .red { /*...*/ }
  .green { /*...*/ }
  .blue { /*...*/ }
}
```

### Configure a custom extension for modules

One approach some folks have had success with, especially when migrating from global CSS to CSS Modules, is to make the name rewriting opt-in by configuring a custom extension:

```js
cssModules: {
  extension: ['module.css']
}
```

With config like ☝️, only files named `foo.module.css` will be treated as isolated modules, and anything ending in plain `.css` will still be global.

### Reference the local class from your app

Instead of forcing the class to be global, another option is to update your template to indicate where the class you're trying to use comes from:

```hbs
<span class={{local-class "red" from="my-addon/styles/foo"}}>
  I am red because the .red class is provided by my-addon
</span>
```

### Compose the addon class from an app class

This is generally how we manage these sorts of utility classes in all our internal addons and applications.

```css
/* app/styles/application.css */
.my-block-of-text {
  composes: red from 'my-addon/styles/foo';
  composes: padding-large centered from 'my-addon/styles/layout';
  /* additional custom styles here */
}
```

```hbs
{{! app/templates/application.hbs }}
<span local-class="my-block-of-text">
  I am red because the .red class is provided by my-addon
</span>
```
