### ISSUE TITLE
Can you use :global in a components' css?

### ISSUE THREAD

**Issue by NullVoxPopuli** [salsify/ember-css-modules#169]
I'm migrating from all global styles, and I'm wanting to do that incrementally, rather than all at once, but I've been running in to a lot of issues :(

mainly right now (for this issue#), it seems that in component styles, `:global {}` has no effect?

**Comment by buschtoens** [comment]
Can you give a complete snippet of code using `:global`, describe what it _should_ do and what it _actually_ does?

I never had issues with `:global` so far.

**Comment by buschtoens** [comment]
Ah, I guess you mean [#170](https://github.com/salsify/ember-css-modules/pull/170/files)?

**Comment by buschtoens** [comment]
What is your PostCSS configuration? You need to use [`postcss-nested`](https://github.com/postcss/postcss-nested) as a [`before` plugin](https://github.com/salsify/ember-css-modules/blob/master/docs/POSTCSS.md#beforeafter-postcss-plugins), so that is is applied, before `css-modules` tries to process `:global`.

This is the config that I am using: [`@clark/ember-css-modules-config`](https://github.com/ClarkSource/ember-css-modules-config/blob/master/lib/clark-plugin.js)
The code you added in #170 does what you'd want it to do with that config.

**Comment by NullVoxPopuli** [comment]
here is what I'm doing so far:
```css
:global {
  .top-nav {
    @apply --no-select;
    @apply --column-grid;
    @apply --grid-space-betwen;

    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    height: var(--top-nav-height);
    background: var(--top-nav-bg);
    box-shadow: var(--top-nav-shadow);
    padding-left: var(--grid-gap);
    padding-right: var(--grid-gap);

    justify-items: start;

    z-index: 100;
  }
```
the global now works with:
```ts
  cssModules: {
      // config for https://github.com/salsify/broccoli-css-modules#plugins
      plugins: {
        before: [
          // needed to support :global
          PostCSSNested(),
          // @apply dosent' work in after? -- still trying to figure this one out
          PostCSSApply({ preserve: true }),
        ],
        after: [
          // needed to prevent shoelace from becoming local-ized
          PostCSSImport({
            path: ['node_modules/shoelace-css/source/css'],
          }),
          // postcss transform needs to be after shoelace so that the styles are transform properly...
          PostCSSNext({
            features: {
              applyRule: false, // would be duplicate otherwise
              colorFunction: {
                preserveCustomProps: false,
              },
              customProperties: {
                preserve: true,
              },
              rem: false, // feature I don't care about
              autoprefixer: false, // this is already included
            },
          }),
        ],
      },
    },
```

thanks for the link to that config, I'll check it out and report back
