### ISSUE TITLE
Shared custom properties and @values

### ISSUE THREAD

**Issue by max** [salsify/ember-css-modules#19]
In our current codebase we `@import "basscss";` and then a the bottom of the `app.css` file have a `:root` with a bunch of custom properties. Here is an example:

```css
/* my-app/styles/app.css */
@import "basscss";

.some-component {
  margin-bottom: var(--space-1);
}

:root {
  --space-1: 1rem;
}
```

Setting the custom property will affect both Basscss and the component code. Basscss happens to have a bunch of spacer classes (`.mb1`, `.mb2`, etc.) that make use of `--space`. These classes are great but sometimes it is more idiomatic to write:

```html
<div class="my-component">Hello World</div>

<!-- vs -->

<div class="my-component mb1">Hello World</div>
```

By being able to use the same custom properties in both our utility libraries and components we get a nice level of consistency. I tried rebuilding this with a contrived use of `@value` but didn't succeed. Any pointers for this scenario?

**Comment by max** [comment]
Another alternative I tried is to use `compose` which would be fantastic for Basscss class extension but since imports don't happen until `after` there is nothing to compose. Adding `import` to `before` means all the classes get rewritten.

**Comment by dfreeman** [comment]
There's an [undocumented feature](https://github.com/css-modules/postcss-modules-scope/commit/d476194758c7ecf17b0f2d19b93ea32ac3a758e6) of the class composition plugin that allows you to compose a global class without having to prove it exists.

```css
.some-component {
  composes: global(mb1);
}
```

Will that work for your case? I'll open up a doc issue on that repo as well as one here to make sure it gets documented.

The other alternative (or maybe complementary technique) would be to introduce `@value`s for the properties you want to share and then pipe those to both your Basscss config and the components in question.

```css
/* app/styles/constants.css */
@value --space-1: 1rem;
```

```css
/* app/styles/third-party.css */
@value --space-1 as --space-1-value from './constants';

:root {
  --space-1: --space-1-value;
}
```

```css
/* app/components/my-component/styles.css */
@value --space-1 from 'things/styles/constants';
.some-component {
  margin-bottom: --space-1;
}
```

The up side is you have a nice clear record of where each value is coming from; the down side is that you can't just "inherit" any of the values in Basscss and reuse them elsewhere, and there's a fair amount of boilerplate.
