### ISSUE TITLE
@values with commas and quotes in them?

### ISSUE THREAD

**Issue by max** [salsify/ember-css-modules#22]
Is it possible to have a `@value` for a `font-family`?

```css
@value --font-family: "Helvetica Neue", Arial, Geneva, sans-serif;

.foobar {
  font-family: --font-family;
}

/* yields */

.foobar {
  font-family: "Helvetica Neue";
}
```
