### ISSUE TITLE
postcss-color-function support

### ISSUE THREAD

**Issue by max** [salsify/ember-css-modules#23]
Currently it isn't possible to use an imported `@value` in a PostCSS color function. For example:

```css
@value --light-gray from "things/styles/colors";

.foobar {
  background: color(--light-gray alpha(50%));
}
```

This results in:

```
Unable to parse color from string "i__const___light_gray_473"
```

By comparison this works fine:

```css
@value --light-gray: #999;

.foobar {
  background: color(--light-gray alpha(50%));
}
```

I also tried moving `postcss-color-function` to the before hook but then the error message is:

```
Unable to parse color from string "--light-gray"
```

Which makes sense given that at that stage it's just a string.
