### ISSUE TITLE
Unable to use composition with localClassNameBindings array

### ISSUE THREAD

**Issue by ynnoj** [salsify/ember-css-modules#54]
I'm trying to use the `localClassNameBindings` array with a single computed property that returns a class that use the `composes` functionality provided by this add-on. See the basic example below.

`classNameBindings must not have spaces in them. Multiple class name bindings can be provided as elements of an array, e.g. ['foo', ':bar']`

```js
import Ember from 'ember';

const { Component, computed } = Ember;

export default Component.extend({
  localClassNames: ['stock-indicator'],
  localClassNameBindings: ['outOfStock:stock-indicator--unavailable:stock-indicator--available'],

  outOfStock: computed.equal('stock.availability', 'out-stock'),

});
```

```css
.stock-indicator {
  composes: white px1 rounded from global;
}

  .stock-indicator--available {
    composes: bg-blue from global;
  }

  .stock-indicator--unavilable {
    composes: bg-red from global;
  }
```
