### ISSUE TITLE
Ember test hangs if there is a specific dependency chain.

### ISSUE THREAD

**Issue by robert-j-webb** [salsify/ember-css-modules#83]
I'm using ember-css-module: 0.7.3, ember-cli: 2.15.1, node: 8.4.0

This bug only happens with ember test, and it only happens when I have this specific dependency chain: 

file-0.css
```css
:global .foo{
  color: red;
}
```

file-1.css

```css
.foo {
  composes: foo from global;
  color: green;
}
```

file-2.css

```css
.foo {
  composes: foo from 'nlroot/**/styles.css';
  color: green;
}
```

I wasn't able to reproduce this in a test repo. It may be a combination of plugins and build interacting with each other.
