### ISSUE TITLE
Default import for pod styles

### ISSUE THREAD

**Issue by buschtoens** [salsify/ember-css-modules#89]
When using pod style components it's a bit tedious to always have to append `/styles` to the import path for `@value` and `composes`.

If the given path resolves to a directory, e-c-s should automatically try to load a `styles.${defaultExtension}` file from it. This way the user can omit `/styles`.

For instance:

```css
@value header-height as overlap from "auswertung-top/components/data-table/styles";

.header {
  composes: wrapper from "auswertung-top/application/styles";

  padding-bottom: overlap;
}
```

becomes:

```cs
@value header-height as overlap from "auswertung-top/components/data-table";

.header {
  composes: wrapper from "auswertung-top/application";

  padding-bottom: overlap;
}
```

The only complication I can see is, that `resolve-path.js` currently does the resolution synchronously without accessing the file system.
