### ISSUE TITLE
Exporting a selector

### ISSUE THREAD

**Issue by buschtoens** [salsify/ember-css-modules#90]
This is probably something that should be brought up in the CSS modules repository, but I'm interested in your opinion / ideas first.

Currently I do not see an easy way to extend classes (or generally selectors) of a third party addon, that is also using ember-css-modules.

I have two concrete examples:

#### Extending a plain local class

[`ember-radio-bar/components/radio-bar/styles.css`](https://github.com/buschtoens/ember-radio-bar/blob/944a074a15d2a0088ee43bfae637f0c69a245d7f/addon/components/radio-bar/styles.css)

```css
.radio-bar {
  display: inline-flex;
  user-select: none;
}
```

How would I, as a user of that addon, specify a style that should apply to *all* `.radio-bar` elements that are children of my own local class? If `.radio-bar` was a global class, I could just do this:

```css
.my-local-class :global(.radio-bar) {
  background: green;
}
```

But since it isn't, I'd need something similar to the `{{local-class ... from=...}}` template helper.

```hbs
{{local-class "radio-bar" from="ember-radio-bar/components/radio-bar/styles"}}
```

```css
.my-local-class :local(.radio-bar, "ember-radio-bar/components/radio-bar/styles") {
  background: green;
}
```

#### Explicitly exporting a complex selector

[`ember-radio-bar/components/radio-bar/button/styles.css`](https://github.com/buschtoens/ember-radio-bar/blob/944a074a15d2a0088ee43bfae637f0c69a245d7f/addon/components/radio-bar/button/styles.css#L16-L22)

```css
.button {
  /* ... */

  .radio:focus + & {
    outline: solid;
  }

  .radio:checked + & {
    background: blue;
  }

  /* ... */
}
```

In this case I would like to explicitly export the `:focus` and `:checked` selectors, so that the user can use them to style these states.

For example something like this:

```css
.button {
  .radio:focus + & {
    export-as: button--focus;
  }

  .radio:checked + & {
    export-as: button--checked;
  }

  /* ... */
}
```

```css
.my-local-class :local(.button--focus, "ember-radio-bar/components/radio-bar/button/styles") {
  outline: solid;
}

.my-local-class :local(.button--checked, "ember-radio-bar/components/radio-bar/button/styles") {
  background: blue;
}
```

---

The proposed syntax and keywords are probably not the best idea and are just a shot in the dark, but I hope it gets the point across. [Custom selectors](https://github.com/postcss/postcss-custom-selectors) may offer a standardized solution.
